######################################################################
# Automatically generated by qmake (3.0) mer. sept. 27 11:48:33 2017
######################################################################

TEMPLATE = app
TARGET = "test"
INCLUDEPATH += .
QT += widgets
CONFIG += c++14

# Input
SOURCES += main.cpp window.cpp 
HEADERS += window.h 
